export interface Preceito {
    num: string
    title: string;
}

export const preceitos: Preceito[] = [
    { title: `O outro em primeiro lugar. ` },
    { title: `Se em toda a existência o CVV salvar uma vida, o trabalho se justifica. ` },
    { title: `Lutar pela vida ainda é o melhor. ` },
    { title: `A fé sem obras é morta. ` },
    { title: `Obrigar-se a fazer é disciplina. Sem ela nada conseguiremos. ` },
    { title: `Não faça para agradar. ` },
    { title: `Se não veio para ajudar, não atrapalhe. ` },
    { title: `Todo trabalho deve ser feito com seriedade e responsabilidade. ` },
    { title: `O ideal é mais importante que o personalismo dos voluntários. ` },
    { title: `Saber fazer sem dizer ou mostrar que se sabe, comportando-se discreta e confiantemente. ` },
    { title: `Comentar o mal é dar força a ele. ` },
    { title: `Concedei-nos Senhor, a serenidade para aceitar as coisas que não podemos modificar, coragem para modificar as que podemos, e sabedoria para distinguir umas das outras. ` },
    { title: `Durante o plantão o voluntário fica em disponibilidade para salvar vidas. ` },
    { title: `Durante o plantão o voluntário usa o tempo somente para os interesses do plantão. ` },
    { title: `Só é admitida recusa de atendimento quando a segurança do voluntário é comprometida. ` },
    { title: `O serviço é gratuito. Como voluntários não fazemos mais que a obrigação. ` },
    { title: `O grupo é mais importante que o personalismo dos voluntários. ` },
    { title: `A participação é aberta a todos que queiram colaborar desinteressadamente. ` },
    { title: `Para tornar-se voluntário é preciso participar de um curso de seleção. ` },
    { title: `No trabalho em grupo não se muda por mudar, especialmente se o trabalho está correto e feito com esforço. ` },
    { title: `No grupo mudanças aleatórias e consecutivas desestabilizam. ` },
    { title: `As regras são iguais para todos. ` },
    { title: `Ninguém fiscaliza o trabalho individual dos voluntários. Existe a confiança que cada um esteja fazendo o melhor. ` },
    { title: `Todos os plantonistas são voluntários. ` },
    { title: `É possível ser um participante sem cargo, mas sempre com algum encargo. ` },
    { title: `É mais eficiente estudar e programar em grupos pequenos. ` },
    { title: `Os planos de ação têm que ser atribuídos a pessoas ou grupos de trabalho mas cobrados só de uma pessoa. ` },
    { title: `Quem dá a idéia é alguém que tem o potencial de fazer mais e melhor. ` },
    { title: `Para fazer o bem é preciso organizar. ` },
    { title: `Para realizar um plano de ação é preciso ter controles, cobranças e cooperação. ` },
    { title: `Os “mais velhos”, aqueles que assumem e testemunham, são os que coordenam. ` },
    { title: `Os “mais velhos” são aqueles que assumem trabalho e encargos e praticam estes princípios. ` },
    { title: `O coordenador de grupo, posto ou regional, representa e facilita o grupo e tem seu voto de confiança, assim pode cobrar e ser cobrado. ` },
    { title: `O coordenador não pode ser teórico, inativo ou indiferente. ` },
    { title: `O personalismo, a politicagem e o melindre geram brigas, rupturas e separações; minam com o trabalho e não podem ser aceitos internamente.(Não há registro de briga entre os “mais velhos”). ` },
    { title: `O voluntário que agiu de má fé não está em condições de continuar. ` },
    { title: `No trabalho voluntário não se agradece nem se paga ao voluntário pela sua participação. ` },
    { title: `Quem não está de acordo com a sistemática do trabalho deve procurar outro. ` },
    { title: `Ninguém é insubstituível, todos são importantes. ` },
    { title: `Confraternizar para melhor servir. ` },
    { title: `Treinar para melhor servir. ` },
    { title: `A relação de ajuda se baseia na aceitação, compreensão, respeito e comunicação. ` },
    { title: `Para fazer bem é indispensável se preparar, entrando em sintonia espiritual com o trabalho. ` },
    { title: `Um dos esforços constantes para manter o trabalho vivo é a comunicação. ` },
    { title: `Uma das características do voluntário é a capacidade de renunciar. ` },
    { title: `“Se todos fizerem o que estou fazendo, como ficarão as coisas no Posto?”. ` },
    { title: `Quando o trabalhador está pronto o serviço aparece. ` },
    { title: `Manter-se sempre no trabalho. Quem se afasta dificilmente retorna, ` },
    { title: `O voluntário paga para trabalhar. ` },
    { title: `Preguiça não. Trabalhar! Trabalhar! Trabalhar! ` },
    { title: `O sigilo é a base do trabalho. ` },
    { title: `O CVV não é um clube de amigos. ` },
].map( (item, index) =>({
    num: String(index + 1),
    ...item,
}))